version: 2
jobs:
  build:
    branches:
      only:
        - circleci-project-setup
 
    docker:
      # specify the version you desire here
      - image: circleci/node:10.12.0
 
    working_directory: ~/repo
 
    steps:
 
      - checkout
      - run: sh test.sh
